---

namespace: artis3n
name: github
version: 1.0.0
readme: README.md
authors:
  - Ari Kalfus (@artis3n) <dev@quantummadness.com>
description: This lookup returns the latest tagged release version of a Github repository.
license_file: LICENSE
tags:
  - github
  - repository
  - version
repository: https://github.com/artis3n/ansible-collection-github
documentation: https://github.com/artis3n/ansible-collection-github
issues: https://github.com/artis3n/ansible-collection-github/issues
