---

namespace: artis3n
name: github
version: 1.0.0
readme: README.md
authors:
  - Ari Kalfus (@artis3n) <dev@artis3nal.com>
description: This collection contains playbooks, roles, modules, and plugins to manage GitHub tasks.
license_file: LICENSE
tags:
  - github
  - repository
  - version
repository: https://github.com/artis3n/ansible-collection-github
documentation: https://github.com/artis3n/ansible-collection-github
issues: https://github.com/artis3n/ansible-collection-github/issues
