---
- name: Converge
  hosts: all

  collections:
    - artis3n.github

  tasks:
    - name: Test the module
      debug:
        msg: "{{ lookup('artis3n.github.latest_release', 'ansible/ansible') }}"
